service: go-sls-auction
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    SERVICE: ${self:service}
    STAGE: ${sls:stage}
    REGION: ${self:provider.region}
    DYNAMODB_TABLE: ${self:custom.AuctionsTable.name}
  iam:
    role:
      statements:
      - ${file(iam/auctions-table-iam.yml):AuctionsTableIAM}
      - ${file(iam/auctions-table-iam.yml):DynamoListAll}
    
package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  dbHealth: ${file(cmd/dbhealth/dbhealth.yml):dbHealth}
  createAuction: ${file(cmd/createAuction/create-auction.yml):createAuction}

resources:
  Resources:
    AuctionsTable: ${file(resources/auctions-table.yml):AuctionsTable}

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn 