service: go-sls-auction
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    SERVICE: ${self:service}
    STAGE: ${sls:stage}
    REGION: ${self:provider.region}
    DYNAMODB_TABLE: ${self:service}-table-${sls:stage}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  createAuction:
    handler: bin/createAuction
    events:
      - httpApi:
          path: /auction
          method: POST
resources:
  Resources:
    auctionTable:
      Type: AWS::DynamoDB::Table
      Properties:  
        TableName: ${self:service}-table-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH