---
AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:  
    TableName: ${self:service}-table-${sls:stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH